"""empty message

Revision ID: 2c10c48525f9
Revises: 366efe1248f4
Create Date: 2015-01-29 19:47:50.693654

"""

# revision identifiers, used by Alembic.
revision = '2c10c48525f9'
down_revision = '366efe1248f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
