"""empty message

Revision ID: 34f1f752ac
Revises: None
Create Date: 2015-01-31 16:37:55.120748

"""

# revision identifiers, used by Alembic.
revision = '34f1f752ac'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
