"""empty message

Revision ID: 366efe1248f4
Revises: 49df622b9e42
Create Date: 2015-01-29 13:07:27.688254

"""

# revision identifiers, used by Alembic.
revision = '366efe1248f4'
down_revision = '49df622b9e42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
