"""empty message

Revision ID: 4323fd299e99
Revises: 34f1f752ac
Create Date: 2015-01-31 17:24:11.570808

"""

# revision identifiers, used by Alembic.
revision = '4323fd299e99'
down_revision = '34f1f752ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('views', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'views')
    ### end Alembic commands ###
