"""empty message

Revision ID: 4b0f37582562
Revises: 6f398577753
Create Date: 2015-01-30 02:49:43.052180

"""

# revision identifiers, used by Alembic.
revision = '4b0f37582562'
down_revision = '6f398577753'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'answers_author_name_fkey', 'answers', type_='foreignkey')
    op.drop_column('answers', 'author_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('author_name', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'answers_author_name_fkey', 'answers', 'users', ['author_name'], ['id'])
    ### end Alembic commands ###
