"""empty message

Revision ID: 4cc1cf636d65
Revises: None
Create Date: 2015-01-30 03:29:04.263691

"""

# revision identifiers, used by Alembic.
revision = '4cc1cf636d65'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
