"""empty message

Revision ID: 6f398577753
Revises: 2c10c48525f9
Create Date: 2015-01-30 00:02:36.044987

"""

# revision identifiers, used by Alembic.
revision = '6f398577753'
down_revision = '2c10c48525f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
