"""empty message

Revision ID: 9ce5a30659f
Revises: None
Create Date: 2015-02-01 22:08:39.547134

"""

# revision identifiers, used by Alembic.
revision = '9ce5a30659f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
